-- Every reported row, typed, with its quarantine flags and the route; nothing removed here.
select
    flight_id,
    source_file,
    source_row,
    year,
    month,
    day_of_month,
    day_of_week,
    flight_date,
    carrier,
    tail_number,
    flight_number,
    origin,
    origin_city,
    origin_state,
    dest,
    dest_city,
    dest_state,
    origin || '-' || dest as route,
    crs_dep_local,
    dep_local,
    crs_arr_local,
    arr_local,
    cast(crs_dep_local // 60 as integer) % 24 as dep_hour,
    dep_delay,
    arr_delay,
    taxi_out,
    taxi_in,
    air_time,
    crs_elapsed,
    actual_elapsed,
    distance,
    coalesce(cancelled, false) as cancelled,
    cancellation_code,
    coalesce(diverted, false) as diverted,
    cause_carrier,
    cause_weather,
    cause_nas,
    cause_security,
    cause_late_aircraft,
    total_add_gtime,
    div_airport_landings,
    div1_airport,
    q_duplicate_key,
    q_actual_without_scheduled,
    q_impossible_time,
    q_elapsed_mismatch,
    q_status_conflict,
    q_missing_actual,
    q_cause_mismatch,
    q_tail_missing,
    q_tail_format,
    q_revision,
    {{ excluded_everywhere() }} as excluded
from {{ source('bts', 'flights') }}
