-- The analysis grain: one row per scheduled flight that passed every rule that excludes a row from
-- everything. Cancelled and diverted flights stay (they are the cancellation and diversion rates);
-- each chapter states which of them it uses.
select
    f.flight_id,
    f.flight_date,
    f.year,
    f.month,
    f.day_of_month,
    f.day_of_week,
    f.carrier,
    f.tail_number,
    f.flight_number,
    f.origin,
    f.dest,
    f.route,
    f.origin_state,
    f.dest_state,
    f.dep_hour,
    f.crs_dep_local,
    f.crs_arr_local,
    f.sched_dep_utc,
    f.sched_arr_utc,
    f.dep_delay,
    f.arr_delay,
    f.taxi_out,
    f.taxi_in,
    f.air_time,
    f.crs_elapsed,
    f.actual_elapsed,
    f.distance,
    f.cancelled,
    f.cancellation_code,
    f.diverted,
    f.cause_carrier,
    f.cause_weather,
    f.cause_nas,
    f.cause_security,
    f.cause_late_aircraft,
    not (f.q_tail_missing or f.q_tail_format) as tail_ok,
    not f.q_cause_mismatch as cause_ok,
    a.type_code,
    a.year_built,
    a.registry_file,
    u.unimpeded,
    f.crs_elapsed - u.unimpeded as padding,
    wo.precipitation as origin_precipitation,
    wo.snowfall as origin_snowfall,
    wo.wind_gusts_10m as origin_wind_gusts,
    wo.wind_speed_10m as origin_wind_speed,
    wo.cloud_cover_low as origin_low_cloud,
    wo.temperature_2m as origin_temperature,
    wo.fog as origin_fog,
    wo.thunder as origin_thunder,
    wo.freezing as origin_freezing,
    wd.precipitation as dest_precipitation,
    wd.snowfall as dest_snowfall,
    wd.wind_gusts_10m as dest_wind_gusts,
    wd.wind_speed_10m as dest_wind_speed,
    wd.cloud_cover_low as dest_low_cloud,
    wd.temperature_2m as dest_temperature,
    wd.fog as dest_fog,
    wd.thunder as dest_thunder,
    wd.freezing as dest_freezing,
    (wo.airport is not null and wd.airport is not null) as weather_both_ends
from {{ ref('int_flights_utc') }} f
left join {{ ref('stg_aircraft') }} a on a.tail_number = f.tail_number
left join {{ ref('int_unimpeded') }} u
    on u.route = f.route and u.hour_block = {{ hour_block('f.dep_hour') }} and u.season = {{ season('f.month') }}
left join {{ ref('stg_weather') }} wo on wo.airport = f.origin and wo.hour_utc = date_trunc('hour', f.sched_dep_utc)
left join {{ ref('stg_weather') }} wd on wd.airport = f.dest and wd.hour_utc = date_trunc('hour', f.sched_arr_utc)
