// Copies what the site serves as static files and cannot import (the DuckDB-WASM bundles, self
// hosted, never from a CDN) and writes the color tokens for both themes from the validated palette.
// Light is the default: the story is a long read on newsprint. Dark is a full theme the reader
// chooses, built for the explorer and the data pages; print always takes light.
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pub = join(root, "public");
const duck = join(root, "node_modules", "@duckdb", "duckdb-wasm", "dist");
mkdirSync(join(pub, "duckdb"), { recursive: true });
let copied = 0;
for (const file of ["duckdb-eh.wasm", "duckdb-browser-eh.worker.js"]) {
  if (existsSync(join(duck, file))) {
    copyFileSync(join(duck, file), join(pub, "duckdb", file));
    copied += 1;
  }
}
if (copied !== 2) throw new Error("the DuckDB-WASM bundles are missing from node_modules; run npm ci first");

const palette = JSON.parse(readFileSync(join(root, "src", "theme", "palette.json"), "utf8"));
const block = (mode, indent, important = false) => {
  const p = palette[mode];
  const lines = [
    `--surface: ${p.surface};`,
    `--raised: ${p.raised};`,
    `--hairline: ${p.hairline};`,
    `--ink: ${p.ink};`,
    `--ink2: ${p.ink2};`,
    `--control: ${p.control};`,
    `--lead: ${p.categorical[0]};`,
    ...p.categorical.map((c, i) => `--cat-${i + 1}: ${c};`),
    ...p.sequential.map((c, i) => `--seq-${i + 1}: ${c};`),
    ...p.diverging.map((c, i) => `--div-${i + 1}: ${c};`),
    `--mid: ${p.diverging[Math.floor(p.diverging.length / 2)]};`,
    ...Object.entries(p.status).map(([k, c]) => `--${k}: ${c};`),
    `color-scheme: ${mode};`,
  ];
  return lines.map((l) => `${indent}${important ? l.replace(/;$/, " !important;") : l}`).join("\n");
};
writeFileSync(
  join(root, "src", "app", "tokens.css"),
  `/* Generated by scripts/prepare-assets.mjs from src/theme/palette.json. Do not edit. */\n` +
    `:root {\n${block("light", "  ")}\n}\n\n` +
    `:root[data-theme="dark"] {\n${block("dark", "  ")}\n}\n\n` +
    `@media print {\n  :root {\n${block("light", "    ", true)}\n  }\n}\n`,
);
console.log("prepared: DuckDB-WASM bundles and the color tokens (light first)");
