{# Generated by scripts/build_warehouse_sql.py from turnaround_rotations.reconstruct.full_sql. Do not edit by hand. #}
{#
  int_legs is built in buckets of tail numbers: the model's statement writes the first bucket and a
  post hook inserts each of the others, in the same transaction. Every window in the reconstruction
  is partitioned by the tail, or by the rotation or the tail's day, both inside one tail, so a bucket
  holds whole partitions and the buckets together are exactly what one statement would give. One
  statement over every flown leg sorted the whole table once per window and spilled more than the
  build machine's disk held.
#}
{% macro int_legs_bucket(source, bucket, buckets) -%}
select
        *,
        row_number() over (partition by rotation_id order by sched_dep_utc, flight_id) as leg_index,
        count(*) over (partition by rotation_id) as rotation_legs,
        row_number() over (partition by tail_number, flight_date order by sched_dep_utc, flight_id) as day_leg_index
    from (
    with legs as (
        select
            flight_id, flight_date, carrier, tail_number, origin, dest, dep_hour,
            sched_dep_utc, sched_arr_utc, dep_delay, arr_delay,
            sched_dep_utc + to_minutes(cast(dep_delay as bigint)) as actual_dep_utc,
            sched_arr_utc + to_minutes(cast(arr_delay as bigint)) as actual_arr_utc
        from {{ source }}
        where not cancelled and not diverted and tail_number is not null
          and dep_delay is not null and arr_delay is not null and sched_dep_utc is not null
          and hash(tail_number) % {{ buckets }} = {{ bucket }}
    ),
    ordered as (
        select
            *,
            lag(flight_id) over w as prev_flight_id,
            lag(dest) over w as prev_dest,
            lag(sched_arr_utc) over w as prev_sched_arr_utc,
            lag(actual_arr_utc) over w as prev_actual_arr_utc,
            lag(arr_delay) over w as prev_arr_delay,
            lag(carrier) over w as prev_carrier
        from legs
        window w as (partition by tail_number order by sched_dep_utc, flight_id)
    ),
    statused as (
        select
            *,
            date_diff('minute', prev_sched_arr_utc, sched_dep_utc) as sched_turn,
            date_diff('minute', prev_actual_arr_utc, actual_dep_utc) as actual_turn,
            case
                when prev_flight_id is null then 'first'
                when date_diff('minute', prev_sched_arr_utc, sched_dep_utc) > 360.0 then 'gap'
                when prev_dest <> origin then 'broken_chain'
                when sched_dep_utc < prev_sched_arr_utc or actual_dep_utc < prev_actual_arr_utc then 'impossible'
                else 'linked'
            end as link_status
        from ordered
    )
    select
        *,
        tail_number || ':' || cast(
            sum(case when link_status = 'linked' then 0 else 1 end)
                over (partition by tail_number order by sched_dep_utc, flight_id rows unbounded preceding)
            as varchar
        ) as rotation_id
    from statused
    )
{%- endmacro %}

{% macro int_legs_hooks(buckets) -%}
    {%- set hooks = [] -%}
    {%- for b in range(1, buckets) -%}
        {%- do hooks.append(
            "insert into {{ this }} by name {{ int_legs_bucket(ref('fct_flights'), " ~ b ~ ", " ~ buckets ~ ") }}"
        ) -%}
    {%- endfor -%}
    {{ return(hooks) }}
{%- endmacro %}
