"""The warehouse models generated from Python, so one implementation serves the simulator and the flights.

int_unimpeded comes from turnaround_chapters.padding and int_legs from turnaround_rotations.reconstruct.
scripts/build_warehouse_sql.py writes them; a test and the warehouse stage refuse stale copies.
"""

from __future__ import annotations

from pathlib import Path

from turnaround_chapters.padding import unimpeded_sql
from turnaround_core.config import POLICY
from turnaround_core.paths import paths
from turnaround_rotations.reconstruct import full_sql

HEADER = "-- Generated by scripts/build_warehouse_sql.py from {origin}. Do not edit by hand.\n"

# int_legs is built one bucket of tail numbers at a time. A single statement over every flown leg
# sorted the whole table once for each window and spilled more temporary data than the build
# machine's disk held; a bucket sorts in memory.
LEGS_NOTE = """{#
  int_legs is built in buckets of tail numbers: the model's statement writes the first bucket and a
  post hook inserts each of the others, in the same transaction. Every window in the reconstruction
  is partitioned by the tail, or by the rotation or the tail's day, both inside one tail, so a bucket
  holds whole partitions and the buckets together are exactly what one statement would give. One
  statement over every flown leg sorted the whole table once per window and spilled more than the
  build machine's disk held.
#}
"""
HOOKS_MACRO = """{% macro int_legs_hooks(buckets) -%}
    {%- set hooks = [] -%}
    {%- for b in range(1, buckets) -%}
        {%- do hooks.append(
            "insert into {{ this }} by name {{ int_legs_bucket(ref('fct_flights'), " ~ b ~ ", " ~ buckets ~ ") }}"
        ) -%}
    {%- endfor -%}
    {{ return(hooks) }}
{%- endmacro %}
"""


def models() -> dict[Path, str]:
    fit = "not excluded and year between {{ var('fit_first_year') }} and {{ var('fit_last_year') }}"
    unimpeded = unimpeded_sql(
        "{{ ref('stg_flights') }}", fit, POLICY.unimpeded_percentile, POLICY.padding_min_flights
    )
    legs = full_sql("{{ source }}", POLICY.rotation_gap_hours, bucket=("{{ bucket }}", "{{ buckets }}"))
    origin = "turnaround_rotations.reconstruct.full_sql"
    return {
        paths().root
        / "warehouse/models/intermediate/int_unimpeded.sql": "{{ config(materialized='table') }}\n"
        + HEADER.format(origin="turnaround_chapters.padding.unimpeded_sql")
        + unimpeded.strip()
        + "\n",
        paths().root / "warehouse/models/intermediate/int_legs.sql": (
            "{{ config(materialized='table', post_hook=int_legs_hooks(var('leg_buckets'))) }}\n"
            + HEADER.format(origin=origin)
            + "-- The first bucket of tails; the post hooks insert the others (macros/int_legs.sql says why).\n"
            + "{{ int_legs_bucket(ref('fct_flights'), 0, var('leg_buckets')) }}\n"
        ),
        paths().root / "warehouse/macros/int_legs.sql": (
            "{# "
            + HEADER.format(origin=origin).removeprefix("-- ").strip()
            + " #}\n"
            + LEGS_NOTE
            + "{% macro int_legs_bucket(source, bucket, buckets) -%}\n"
            + legs.strip()
            + "\n{%- endmacro %}\n\n"
            + HOOKS_MACRO
        ),
    }


def stale() -> list[str]:
    return [
        str(p.relative_to(paths().root))
        for p, text in models().items()
        if not p.exists() or p.read_text() != text
    ]
