"""The warehouse models generated from Python, so one implementation serves the simulator and the flights.

int_unimpeded comes from turnaround_chapters.padding and int_legs from turnaround_rotations.reconstruct.
scripts/build_warehouse_sql.py writes them; a test and the warehouse stage refuse stale copies.
"""

from __future__ import annotations

from pathlib import Path

from turnaround_chapters.padding import unimpeded_sql
from turnaround_core.config import POLICY
from turnaround_core.paths import paths
from turnaround_rotations.reconstruct import full_sql

HEADER = "-- Generated by scripts/build_warehouse_sql.py from {origin}. Do not edit by hand.\n"


def models() -> dict[Path, str]:
    fit = "not excluded and year between {{ var('fit_first_year') }} and {{ var('fit_last_year') }}"
    unimpeded = unimpeded_sql(
        "{{ ref('stg_flights') }}", fit, POLICY.unimpeded_percentile, POLICY.padding_min_flights
    )
    legs = full_sql("{{ ref('fct_flights') }}", POLICY.rotation_gap_hours)
    return {
        paths().root
        / "warehouse/models/intermediate/int_unimpeded.sql": "{{ config(materialized='table') }}\n"
        + HEADER.format(origin="turnaround_chapters.padding.unimpeded_sql")
        + unimpeded.strip()
        + "\n",
        paths().root / "warehouse/models/intermediate/int_legs.sql": "{{ config(materialized='table') }}\n"
        + HEADER.format(origin="turnaround_rotations.reconstruct.full_sql")
        + legs.strip()
        + "\n",
    }


def stale() -> list[str]:
    return [
        str(p.relative_to(paths().root))
        for p, text in models().items()
        if not p.exists() or p.read_text() != text
    ]
